### ISSUE TITLE
"Switch" to a newly opened window

### ISSUE THREAD

**Issue by bobdenotter** [TheSoftwareHouse/Kakunin#152]
Hi! 👋 

I'm working on a test where i want to see if something appears in a dynamically opened window. So far, my `.feature` looks like: 

```
Feature: Edit record

    @wip
    Scenario: As an Admin I want to preview an edited record
        Given I am logged in as "admin"

        When I visit the "edit_record" page with parameters:
            | id | 30 |
        Then I wait for "title_field" element to appear

        When I fill the "title_field" field with "Check preview"
        And I click the "preview_button" element
        Then I wait for "frontend_title" element to appear
        Then there is element "frontend_title" with text "Check preview"
```

My `pages/….js` looks like: 

```js
const { BasePage } = require('kakunin');

class EditRecordPage extends BasePage {
  constructor() {
    super();

… 

    this.preview_button = $('button[type="submit"][formaction*="/bolt/preview/"]');

    this.frontend_title = $('h1.title');
  }
}

module.exports = EditRecordPage;
```

I can see it working correctly up until `And I click the "preview_button" element` after which a new browser window is spawned, with the correct contents. 

My question is: how can i tell the test to "switch" to this new window, in order to verify the `frontend_title` contains the text I need? Is this possible?

**Comment by bobdenotter** [comment]
I was given the missing clue by @JarJak : 

```javascript
When(/^I switch to window number "([^"]*)" of a browser$/, tabNumber => {
  return browser.getAllWindowHandles().then(handles => browser.switchTo().window(handles[tabNumber - 1]));
});
```

So i'm using this, and it works like a charm! ✨ 

```
        When I switch to window number "2" of a browser
        Then there is element "frontend_title" with text "Check preview"
```

**Comment by tgorskievo** [comment]
Hello @bobdenotter 

Sorry for the late answer.

Great that you find a solution 👍 Do you have other question about this functionality?

**Comment by bobdenotter** [comment]
Hi @tgorskievo, 

One small follow-up: Can I make Kakunin _close_ the window again? I tried something like `I close window number "2" of a browser`, but that doesn't work.

**Comment by tgorskievo** [comment]
@bobdenotter 
At the moment, there is a step `When I close the current browser tab` which is closing currently opened tab/window and then switches context to the first one.

**Comment by bobdenotter** [comment]
@tgorskievo Ah, excellent! Thanks!
