### ISSUE TITLE
Url parameter wrongly generated

### ISSUE THREAD

**Issue by Damian-B** [TheSoftwareHouse/Kakunin#178]
Try to generate url with parameters. Additional ```0=``` were added to link. 
```
Feature:
    Scenario: Create simple scenario
        When I visit the "main" page with parameters:
            | orderId   | 1 |
```
Current result:
> http://localhost:8080/?0=orderId&0=1

Expected result:
http://localhost:8080/?orderId=1

"kakunin": {
      "version": "3.0.0",

**Comment by tgorskievo** [comment]
Fixed on version 3.0.1
