### ISSUE TITLE
Enable automation of prompts from npm run kakunin init

### ISSUE THREAD

**Issue by wilson-jetbloom** [TheSoftwareHouse/Kakunin#71]
On npm run kakunin init
I am asked three questions which I need to provide input manually:
? What kind of application would you like to test? otherWeb
? What is base url? [http://localhost:3000] http://todomvc.com
? What kind of email service would you like to use? none
But I would like for a script to automatically provide these answers.
After all, the whole point of Kanunin is for automation.

**Comment by wilson-jetbloom** [comment]
In the script I had tried:

## Alternative 1:
<pre>
   npm run kakunin init << EOF
3
http://todomvc.com
1
EOF
</pre>
But that does not result in files being generated.

## Alternative 2:
echo "3 http://todomvc.com 1" | ./kakunin-install.sh
doesn't work either:
? What kind of application would you like to test? 
  1) Angular 1
  2) Angular 2
  3) Other web app (e.g. React, jQuery based etc.)
  Answer: 
>> Please enter a valid index

**Comment by wilson-jetbloom** [comment]
The bash script I am using is 
https://github.com/wilsonmar/DevSecOps/blob/master/Kakunin/kakunin-install.sh

**Comment by sethii** [comment]
@wilson-jetbloom Right now there is no way to skip questions during `init` - this command is only for initialize project structure. 

I think the best approach to skip it, would to pass those answers as command line parameters for example: `npm run kakunin init -- --host http://todomvc.com --emailService none --type otherWeb`.

This would make it possible to run it without answering questions, yet with running project creation code.

I will assign a dev to this task, so we could include it in next minor version.

**Comment by sethii** [comment]
Fixed in `next` branch
