### ISSUE TITLE
Code from @downloadClearAfter tag doesn't remove files that have a space in the name

### ISSUE THREAD

**Issue by TheGeniesis** [TheSoftwareHouse/Kakunin#72]
Hi.
I added tag to remove files when test ends, but it doesn't work when filename contain space.
In situation when I have filename without space everything works good. 

I have this problem when I use docker containers, I didn't check how it works without dockers.

Scenario:
```
Feature: my_feature
  @downloadClearAfter
  Scenario: Download file
    When I click the "button_to_download_file" element
    Then the file "my file.format" should be downloaded
```

Problem:
When test ends downloaded files that have a space in the name are not removed

Expectation:
When test ends downloaded files are always removed

**Comment by simonsipl** [comment]
@tgorskievo @sethii I think we fixed that in "next" branch, Am I right ?

**Comment by simonsipl** [comment]
Hi @TheGeniesis I tried to reproduce but it seems that it doesn't occurs. Please check it again on newest version of kakunin.
